version: '3'
services:

  # --------------------------- #
  # Apache Spark with Delta     #
  # --------------------------- #
  spark-master:
    container_name: spark-master-container
    image: docker.io/bitnami/spark:3.4.1
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
    ports:
      - '8080:8080'
      - '4041:4041'
      - '7077:7077'
    volumes:
      - ./data:/data
      - ./src:/src
    networks:
      - spark-network

  spark-worker:
    container_name: spark-worker-container
    image: docker.io/bitnami/spark:3.4.1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_EXECUTOR_MEMORY=4G
      - SPARK_WORKER_CORES=4
    volumes:
      - ./data:/data
      - ./src:/src
    ports:
      - 8081:8081
    depends_on:
      - spark-master
    networks:
      - spark-network

  jupyter:
    image: jupyter/pyspark-notebook:spark-3.4.1
    container_name: jupyter-container
    environment:
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - "8888:8888"
    volumes:
      - ./src:/home/jovyan/work
    networks:
      - spark-network
    user: root
    command: >
      bash -c "apt update && apt-get install -y jq && apt-get clean && start-notebook.sh --NotebookApp.token=''"

  minio:
    container_name: minio-delta-lake-container
    image: quay.io/minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
   
    volumes:
      - './minio-delta-lake:/data'
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=refatorandopass
      - MINIO_DEFAULT_BUCKETS=your_bucket_name
    networks:
      - spark-network
    command: server --console-address ":9001" /data

      
networks:
  spark-network:
    driver: bridge