# Use a imagem oficial do OpenMetadata Server como base
FROM openmetadata/server:latest

# Alterar para o usuário root para ter permissões suficientes
USER root

# Copiar o script wait-for-it.sh para dentro da imagem
COPY wait-for-it.sh /wait-for-it.sh

# Dar permissões de execução ao script
RUN chmod +x /wait-for-it.sh

# (Opcional) Definir o proprietário do script, se necessário
# RUN chown openmetadata:openmetadata /wait-for-it.sh

# Voltar para o usuário original (substitua 'openmetadata' pelo usuário correto se diferente)
# Consulte a documentação da imagem base para saber o nome do usuário
USER openmetadata

# Definir o ponto de entrada para usar o wait-for-it.sh antes de iniciar o servidor
ENTRYPOINT ["/wait-for-it.sh", "openmetadata-mysql-container:3306", "--"]

# Comando padrão para iniciar o OpenMetadata Server
CMD ["/openmetadata-start.sh"]
