version: '3.8'

services:

  # --------------------------- #
  # Apache Spark with Delta     #
  # --------------------------- #
  spark-master:
    container_name: spark-master-container
    image: docker.io/bitnami/spark:3.4.1
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_LOCAL_DIRS=/tmp/spark-temp
    ports:
      - '8080:8080'
      - '4041:4041'
      - '7077:7077'
    volumes:
      - ./data:/data
      - ./src:/src
      - ./spark-temp:/tmp/spark-temp
    networks:
      - spark-network

  spark-worker-1:
    container_name: spark-worker-1-container
    image: docker.io/bitnami/spark:3.4.1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=3G
      - SPARK_EXECUTOR_MEMORY=1.5G
      - SPARK_WORKER_CORES=2
      - SPARK_LOCAL_DIRS=/tmp/spark-temp
    volumes:
      - ./data:/data
      - ./src:/src
      - ./spark-temp:/tmp/spark-temp
    ports:
      - 8081:8081  # UI do Spark Worker 1
    depends_on:
      - spark-master
    networks:
      - spark-network

  spark-worker-2:
    container_name: spark-worker-2-container
    image: docker.io/bitnami/spark:3.4.1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=3G
      - SPARK_EXECUTOR_MEMORY=1.5G
      - SPARK_WORKER_CORES=2
      - SPARK_LOCAL_DIRS=/tmp/spark-temp
    volumes:
      - ./data:/data
      - ./src:/src
      - ./spark-temp:/tmp/spark-temp
    ports:
      - 8082:8081  # UI do Spark Worker 2 (porta modificada para evitar conflitos)
    depends_on:
      - spark-master
    networks:
      - spark-network

  minio:
    container_name: minio-delta-lake-container
    image: quay.io/minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - './minio-delta-lake:/data'
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=refatorandopass
      - MINIO_DEFAULT_BUCKETS=your_bucket_name
    networks:
      - spark-network
    command: server --console-address ":9001" /data

  jupyter:
    build:
      context: .
      dockerfile: dockerfile.jupyter
    container_name: jupyter-container
    environment:
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - "8888:8888"
    volumes:
      - ./src:/home/jovyan/work
      - ./jars:/home/jovyan/jars
    networks:
      - spark-network
    user: root
    depends_on:
      - spark-master
      - spark-worker-1
      - spark-worker-2
      - minio

  # --------------------------- #
  # MySQL para OpenMetadata    #
  # --------------------------- #

  mysql:
    image: mysql:8.0
    container_name: openmetadata-mysql-container
    environment:
      - MYSQL_ROOT_PASSWORD=abc123
      - MYSQL_DATABASE=openmetadata
      - MYSQL_USER=openmetadata
      - MYSQL_PASSWORD=abc123
    volumes:
      - ./openmetadata_db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - spark-network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  openmetadata-server:
    image: openmetadata/server:latest
    container_name: openmetadata-server-container
    environment:
      - OPENMETADATA_SERVER_PORT=8585
      - OPENMETADATA_DB_HOST=mysql
      - OPENMETADATA_DB_PORT=3306
      - OPENMETADATA_DB_USERNAME=openmetadata
      - OPENMETADATA_DB_PASSWORD=abc123
      - OPENMETADATA_DB_DATABASE=openmetadata
      - OPENMETADATA_DATABASE_TYPE=mysql                  # Especifica o tipo de banco de dados
      - OPENMETADATA_JDBC_URL=jdbc:mysql://mysql:3306/openmetadata?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      # Variáveis adicionais podem ser adicionadas conforme necessário
    ports:
      - "8585:8585"  # Porta padrão do OpenMetadata
    depends_on:
      - mysql
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge
