version: '3.8'

services:

  # --------------------------- #
  # Apache Spark with Delta     #
  # --------------------------- #
  spark-master:
    container_name: spark-master-container
    image: docker.io/bitnami/spark:3.4.1
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_LOCAL_DIRS=/tmp/spark-temp
    ports:
      - '8080:8080'
      - '4041:4041'
      - '7077:7077'
    volumes:
      - ./data:/data
      - ./src:/src
      - ./spark-temp:/tmp/spark-temp
    networks:
      - spark-network

  spark-worker-1:
    container_name: spark-worker-1-container
    image: docker.io/bitnami/spark:3.4.1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=3G
      - SPARK_EXECUTOR_MEMORY=1.5G
      - SPARK_WORKER_CORES=2
      - SPARK_LOCAL_DIRS=/tmp/spark-temp
    volumes:
      - ./data:/data
      - ./src:/src
      - ./spark-temp:/tmp/spark-temp
    ports:
      - 8081:8081  # UI do Spark Worker 1
    depends_on:
      - spark-master
    networks:
      - spark-network

  spark-worker-2:
    container_name: spark-worker-2-container
    image: docker.io/bitnami/spark:3.4.1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=3G
      - SPARK_EXECUTOR_MEMORY=1.5G
      - SPARK_WORKER_CORES=2
      - SPARK_LOCAL_DIRS=/tmp/spark-temp
    volumes:
      - ./data:/data
      - ./src:/src
      - ./spark-temp:/tmp/spark-temp
    ports:
      - 8082:8081  # UI do Spark Worker 2 (porta modificada para evitar conflitos)
    depends_on:
      - spark-master
    networks:
      - spark-network

  minio:
    container_name: minio-delta-lake-container
    image: quay.io/minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - './minio-delta-lake:/data'
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=refatorandopass
      - MINIO_DEFAULT_BUCKETS=your_bucket_name
    networks:
      - spark-network
    command: server --console-address ":9001" /data

  jupyter:
    build:
      context: .
      dockerfile: dockerfile.jupyter
    container_name: jupyter-container
    environment:
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - "8888:8888"
    volumes:
      - ./src:/home/jovyan/work
      - ./jars:/home/jovyan/jars
    networks:
      - spark-network
    user: root
    depends_on:
      - spark-master
      - spark-worker-1
      - spark-worker-2
      - minio

  # --------------------------- #
  # MySQL para Apache Airflow    #
  # --------------------------- #
  mysql-airflow:
    image: mysql:8.0
    container_name: mysql-airflow
    environment:
      - MYSQL_ROOT_PASSWORD=airflow_root_password
      - MYSQL_DATABASE=airflow
      - MYSQL_USER=airflow
      - MYSQL_PASSWORD=airflow_password
    ports:
      - "3308:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - spark-network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # --------------------------- #
  # Apache Airflow              #
  # --------------------------- #
  airflow-webserver:
    build:
      context: .
      dockerfile: dockerfile.airflow
    container_name: airflow-webserver
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__LOGGING__BASE_LOG_FOLDER=/opt/airflow/logs
      - AIRFLOW__LOGGING__LOGGING_LEVEL=INFO
      - AIRFLOW__LOGGING__LOG_FORMAT=[%(asctime)s] {%(filename)s:%(lineno)d} %(levelname)s - %(message)s
      - AIRFLOW__LOGGING__SIMPLE_LOG_FORMAT=%(asctime)s %(levelname)s - %(message)s
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=mysql+mysqlconnector://airflow:airflow_password@mysql-airflow:3306/airflow
      - AIRFLOW__CORE__FERNET_KEY=nK30VckUUKCW1oDiPEagJZxR08hYmTJHjItCPx4UqDU=  # Substitua por uma chave válida
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=True
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=mysql+mysqlconnector://airflow:airflow_password@mysql-airflow:3306/airflow
      - AIRFLOW_ADMIN_USERNAME=admin
      - AIRFLOW_ADMIN_FIRSTNAME=Admin
      - AIRFLOW_ADMIN_LASTNAME=User
      - AIRFLOW_ADMIN_EMAIL=admin@example.com
      - AIRFLOW_ADMIN_PASSWORD=admin
    depends_on:
      - mysql-airflow
    ports:
      - "8086:8080"  # UI do Airflow (host: 8086)
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/scripts:/opt/airflow/scripts
    networks:
      - spark-network
    entrypoint: ["/usr/local/bin/entrypoint_airflow.sh"]

  airflow-scheduler:
    build:
      context: .
      dockerfile: dockerfile.airflow
    container_name: airflow-scheduler
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__LOGGING__BASE_LOG_FOLDER=/opt/airflow/logs
      - AIRFLOW__LOGGING__LOGGING_LEVEL=INFO
      - AIRFLOW__LOGGING__LOG_FORMAT=[%(asctime)s] {%(filename)s:%(lineno)d} %(levelname)s - %(message)s
      - AIRFLOW__LOGGING__SIMPLE_LOG_FORMAT=%(asctime)s %(levelname)s - %(message)s
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=mysql+mysqlconnector://airflow:airflow_password@mysql-airflow:3306/airflow
      - AIRFLOW__CORE__FERNET_KEY=nK30VckUUKCW1oDiPEagJZxR08hYmTJHjItCPx4UqDU=  # Substitua por uma chave válida
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=True
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=mysql+mysqlconnector://airflow:airflow_password@mysql-airflow:3306/airflow
      - AIRFLOW_ADMIN_USERNAME=admin
      - AIRFLOW_ADMIN_FIRSTNAME=Admin
      - AIRFLOW_ADMIN_LASTNAME=User
      - AIRFLOW_ADMIN_EMAIL=admin@example.com
      - AIRFLOW_ADMIN_PASSWORD=admin 
    depends_on:
      - mysql-airflow
      - airflow-webserver
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/scripts:/opt/airflow/scripts
    networks:
      - spark-network
    entrypoint: >
      airflow scheduler

networks:
  spark-network:
    driver: bridge
